### ISSUE TITLE
部分文本需要润色

### ISSUE THREAD

**Issue by ProjectSky** [Mishasama/ProjectZomboidTranslations#35]
* 很久没玩过游戏，也不知道游戏里有什么内容，直到今天群里的一个朋友发了一张图片给我我才发现有些翻译过于难懂和奇怪

> 这些内容是不是太过于突兀了，和游戏内容毫无关系。

https://github.com/Mishasama/ProjectZomboidTranslations/blob/6ab0549e1d6723177f07b2f21ec4e023a1e95c68/CN/Sandbox_CN.txt#L216-L220

> 原文是```Sadistic AI Director``` 直译成```虐待狂 AI 导演```完全让人摸不着头脑。
https://github.com/Mishasama/ProjectZomboidTranslations/blob/6ab0549e1d6723177f07b2f21ec4e023a1e95c68/CN/Sandbox_CN.txt#L384

> 插到？太奇怪了，直接翻译成 ```装备至``` 或 ```装备到``` 更好一点
https://github.com/Mishasama/ProjectZomboidTranslations/blob/6ab0549e1d6723177f07b2f21ec4e023a1e95c68/CN/ContextMenu_CN.txt#L406

* 游戏中的很多东西是要根据实际功能和位置来翻译的，虽然没必要拘于原文，但创造性也不能太强。

**Comment by Mishasama** [comment]
所以官方版本是想要侧重Translation还是Localization呢？
有时候Localization会大幅偏离原文，但相对的会更容易被受众所理解。
而Translation比较原汁原味，但经常由于文化不同而让人摸不着头脑。

也许要针对两种口味的人推出两个版本？还是说要两个并存同时显示出来？

SSR就是尝试Localization的产物，而另外两个就是Translation，众口难调，混搭起来有点难度。

1. 如果觉得很奇怪可以把括号内容去掉。
2. 而那个功能确实是跟“AI”有关的，主要调整的是事件触发的频率。官方的原意就是这样：我们的角色是在拍一部末日生存大片中的一个“演员”，AI作为导演来各种整人，而相关的内容就是虐人的。这可以说是充分还原游戏宗旨的翻译，可能部分对游戏背景不熟悉的玩家会理解不了。建议您对群友做个科普。
3. “插到”改为“挂到”如何？“装备”一词有点机械化的感觉？毕竟官方也不是用的equip而是attach。

**Comment by ProjectSky** [comment]
我个人觉得还是“原汁原味”更适合一点，众口难调，选走一条路就行了。

**Comment by Mishasama** [comment]
> 我个人觉得还是“原汁原味”更适合一点，众口难调，选走一条路就行了。

那……就以高还原度为基准吧，虽然原文对新玩家来说门槛挺高的（比如某些提示文字里说的东西并不很直白）😓
