### ISSUE TITLE
无法解析的部分翻译。

### ISSUE THREAD

**Issue by ProjectSky** [Mishasama/ProjectZomboidTranslations#56]
#### 一些字符串中缺少格式化的标识符，需要添加或修改。

* ContextMenu_CN.txt
```ContextMenu_InsertBullets = "在武器中填装 %1发 %2"```
* 正确的语法
```ContextMenu_InsertBullets  = "Insert %1 %2 in %3"```

* UI_CN.txt
```UI_optionscreen_DblTapRunToSprint = "两次奔跑即可冲刺"```
```UI_optionscreen_DblTapRunToSprintTooltip = "如果选中，则双击奔跑按钮将开始冲刺 \n 按住Shift键可以保持冲刺。"```
* 正确的语法
```UI_optionscreen_DblTapRunToSprint = "Double tap %1 to sprint"```
```UI_optionscreen_DblTapRunToSprintTooltip = "If ticked, double-tapping %1 will start sprinting. \n Hold %2 to continue sprinting."```

**Comment by Mishasama** [comment]
UI 在 #54 已经修了啊……
