### ISSUE TITLE
RadioData_CN.txt 未汉化

### ISSUE THREAD

**Issue by HenryFishYu** [Mishasama/ProjectZomboidTranslations#65]
RadioData_CN.txt  未汉化，目前只是提取了需要汉化的文本，具体怎么实现官方论坛有人问了但是官方还没回复
@ProjectSky 
https://gist.github.com/HenryFishYu/2485045920df988d6030cabca496e3da

**Comment by ProjectSky** [comment]
https://github.com/Mishasama/ProjectZomboidTranslations/issues/67

**Comment by HenryFishYu** [comment]
> #67

copy，我把这个关了
